#!/bin/bash

# NPM & Mermaid-cli is required

mkdir built

for filename in *.md; do
	# We get the filename without the ext
	# filename_no_ext="${filename%.*}"
  ../../node_modules/.bin/mmdc -i "$filename" -o "built/${filename%.*}.md"
done